// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.rs.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

pub mod sym {

    #![allow(
        unused_parens,
        non_snake_case,
        clippy::double_parens,
        clippy::empty_line_after_doc_comments,
        clippy::too_many_arguments,
        clippy::unused_unit,
        unused_variables
    )]

    use stack_algebra::{Float, MatrixScalar, ReductionScalar};
    /// Rust-compatible storage-vector wrapper for the generated update.

    #[inline(always)]
    pub fn imu_manifold_preintegration_update<T: Float + MatrixScalar + ReductionScalar>(
        DR: &symforce_rust::Rot3<T>,
        Dv: &stack_algebra::Matrix<3, 1, T>,
        Dp: &stack_algebra::Matrix<3, 1, T>,
        covariance: &stack_algebra::Matrix<9, 9, T>,
        DR_D_gyro_bias: &stack_algebra::Matrix<3, 3, T>,
        Dv_D_accel_bias: &stack_algebra::Matrix<3, 3, T>,
        Dv_D_gyro_bias: &stack_algebra::Matrix<3, 3, T>,
        Dp_D_accel_bias: &stack_algebra::Matrix<3, 3, T>,
        Dp_D_gyro_bias: &stack_algebra::Matrix<3, 3, T>,
        accel_bias: &stack_algebra::Matrix<3, 1, T>,
        gyro_bias: &stack_algebra::Matrix<3, 1, T>,
        accel_cov_diagonal: &stack_algebra::Matrix<3, 1, T>,
        gyro_cov_diagonal: &stack_algebra::Matrix<3, 1, T>,
        accel_measurement: &stack_algebra::Matrix<3, 1, T>,
        gyro_measurement: &stack_algebra::Matrix<3, 1, T>,
        dt: T,
        epsilon: T,
        new_DR: Option<&mut stack_algebra::Matrix<4, 1, T>>,
        new_Dv: Option<&mut stack_algebra::Matrix<3, 1, T>>,
        new_Dp: Option<&mut stack_algebra::Matrix<3, 1, T>>,
        new_covariance: Option<&mut stack_algebra::Matrix<9, 9, T>>,
        new_DR_D_gyro_bias: Option<&mut stack_algebra::Matrix<3, 3, T>>,
        new_Dv_D_accel_bias: Option<&mut stack_algebra::Matrix<3, 3, T>>,
        new_Dv_D_gyro_bias: Option<&mut stack_algebra::Matrix<3, 3, T>>,
        new_Dp_D_accel_bias: Option<&mut stack_algebra::Matrix<3, 3, T>>,
        new_Dp_D_gyro_bias: Option<&mut stack_algebra::Matrix<3, 3, T>>,
    ) -> () {
        // Total ops: 1272

        // Input storage for geometry values
        let _DR = DR.data();

        // Intermediate terms (336)
        let _tmp0: T = (dt * dt);
        let _tmp1: T = -gyro_bias[0] + gyro_measurement[0];
        let _tmp2: T = _tmp0 * (_tmp1 * _tmp1);
        let _tmp3: T = -gyro_bias[1] + gyro_measurement[1];
        let _tmp4: T = _tmp0 * (_tmp3 * _tmp3);
        let _tmp5: T = -gyro_bias[2] + gyro_measurement[2];
        let _tmp6: T = _tmp0 * (_tmp5 * _tmp5);
        let _tmp7: T = _tmp4 + _tmp6;
        let _tmp8: T = _tmp2 + _tmp7;
        let _tmp9: T = _tmp8 + (epsilon * epsilon);
        let _tmp10: T = _tmp9.sqrt();
        let _tmp11: T = (T::one() / (T::one() + T::one())) * _tmp10;
        let _tmp12: T = _tmp11.cos();
        let _tmp13: T = _tmp11.sin();
        let _tmp14: T = _tmp13 / _tmp10;
        let _tmp15: T = _tmp14 * dt;
        let _tmp16: T = _DR[3] * _tmp15;
        let _tmp17: T = _tmp5 * dt;
        let _tmp18: T = _tmp14 * _tmp17;
        let _tmp19: T = _DR[2] * _tmp15;
        let _tmp20: T = _DR[0] * _tmp15;
        let _tmp21: T = _DR[1] * _tmp15;
        let _tmp22: T = -accel_bias[1] + accel_measurement[1];
        let _tmp23: T = (T::one() + T::one()) * _DR[3];
        let _tmp24: T = _DR[2] * _tmp23;
        let _tmp25: T = (T::one() + T::one()) * _DR[0];
        let _tmp26: T = _DR[1] * _tmp25;
        let _tmp27: T = _tmp24 - _tmp26;
        let _tmp28: T = -_tmp27;
        let _tmp29: T = -accel_bias[2] + accel_measurement[2];
        let _tmp30: T = _DR[1] * _tmp23;
        let _tmp31: T = _DR[2] * _tmp25;
        let _tmp32: T = _tmp30 + _tmp31;
        let _tmp33: T = -accel_bias[0] + accel_measurement[0];
        let _tmp34: T = (T::one() + T::one()) * (_DR[1] * _DR[1]);
        let _tmp35: T = (T::one() + T::one()) * (_DR[2] * _DR[2]) - T::one();
        let _tmp36: T = _tmp34 + _tmp35;
        let _tmp37: T = -_tmp36;
        let _tmp38: T = _tmp22 * _tmp28 + _tmp29 * _tmp32 + _tmp33 * _tmp37;
        let _tmp39: T = _tmp24 + _tmp26;
        let _tmp40: T = _DR[0] * _tmp23;
        let _tmp41: T = (T::one() + T::one()) * _DR[1] * _DR[2];
        let _tmp42: T = _tmp40 - _tmp41;
        let _tmp43: T = -_tmp42;
        let _tmp44: T = (T::one() + T::one()) * (_DR[0] * _DR[0]);
        let _tmp45: T = _tmp35 + _tmp44;
        let _tmp46: T = -_tmp45;
        let _tmp47: T = _tmp22 * _tmp46 + _tmp29 * _tmp43 + _tmp33 * _tmp39;
        let _tmp48: T = _tmp30 - _tmp31;
        let _tmp49: T = -_tmp48;
        let _tmp50: T = _tmp40 + _tmp41;
        let _tmp51: T = _tmp34 + _tmp44 - T::one();
        let _tmp52: T = -_tmp51;
        let _tmp53: T = _tmp22 * _tmp50 + _tmp29 * _tmp52 + _tmp33 * _tmp49;
        let _tmp54: T = (T::one() / (T::one() + T::one())) * _tmp0;
        let _tmp55: T = _tmp8 + epsilon.sqrt();
        let _tmp56: T = _tmp55.sqrt();
        let _tmp57: T = (_tmp56 - _tmp56.sin()) / (_tmp55 * _tmp55.sqrt());
        let _tmp58: T = -_tmp57 * _tmp7 + T::one();
        let _tmp59: T = dt * gyro_cov_diagonal[0];
        let _tmp60: T = (T::one() - _tmp56.cos()) / _tmp55;
        let _tmp61: T = _tmp17 * _tmp60;
        let _tmp62: T = _tmp0 * _tmp1;
        let _tmp63: T = _tmp57 * _tmp62;
        let _tmp64: T = _tmp3 * _tmp63;
        let _tmp65: T = _tmp61 + _tmp64;
        let _tmp66: T = dt * gyro_cov_diagonal[1];
        let _tmp67: T = _tmp60 * dt;
        let _tmp68: T = _tmp3 * _tmp67;
        let _tmp69: T = _tmp5 * _tmp63;
        let _tmp70: T = -_tmp68 + _tmp69;
        let _tmp71: T = dt * gyro_cov_diagonal[2];
        let _tmp72: T = (T::one() + T::one()) * (_tmp13 * _tmp13) / _tmp9;
        let _tmp73: T = _tmp4 * _tmp72;
        let _tmp74: T = _tmp6 * _tmp72 - T::one();
        let _tmp75: T = -_tmp73 - _tmp74;
        let _tmp76: T = _tmp62 * _tmp72;
        let _tmp77: T = _tmp3 * _tmp76;
        let _tmp78: T = (T::one() + T::one()) * _tmp12;
        let _tmp79: T = _tmp18 * _tmp78;
        let _tmp80: T = _tmp77 + _tmp79;
        let _tmp81: T = _tmp5 * _tmp76;
        let _tmp82: T = _tmp15 * _tmp78;
        let _tmp83: T = _tmp3 * _tmp82;
        let _tmp84: T = _tmp81 - _tmp83;
        let _tmp85: T = _tmp57 * (-_tmp2 - _tmp6) + T::one();
        let _tmp86: T = _tmp65 * dt;
        let _tmp87: T = _tmp86 * gyro_cov_diagonal[1];
        let _tmp88: T = -_tmp61 + _tmp64;
        let _tmp89: T = _tmp58 * dt;
        let _tmp90: T = _tmp89 * gyro_cov_diagonal[0];
        let _tmp91: T = _tmp1 * _tmp67;
        let _tmp92: T = _tmp0 * _tmp3 * _tmp5;
        let _tmp93: T = _tmp57 * _tmp92;
        let _tmp94: T = _tmp91 + _tmp93;
        let _tmp95: T = _tmp70 * dt;
        let _tmp96: T = _tmp95 * gyro_cov_diagonal[2];
        let _tmp97: T = _tmp2 * _tmp72;
        let _tmp98: T = -_tmp74 - _tmp97;
        let _tmp99: T = _tmp77 - _tmp79;
        let _tmp100: T = _tmp72 * _tmp92;
        let _tmp101: T = _tmp1 * _tmp82;
        let _tmp102: T = _tmp100 + _tmp101;
        let _tmp103: T = _tmp102 * covariance[(2, 0)]
            + _tmp98 * covariance[(1, 0)]
            + _tmp99 * covariance[(0, 0)];
        let _tmp104: T = _tmp102 * covariance[(2, 1)]
            + _tmp98 * covariance[(1, 1)]
            + _tmp99 * covariance[(1, 0)];
        let _tmp105: T = _tmp102 * covariance[(2, 2)]
            + _tmp98 * covariance[(2, 1)]
            + _tmp99 * covariance[(2, 0)];
        let _tmp106: T = _tmp103 * _tmp75
            + _tmp104 * _tmp80
            + _tmp105 * _tmp84
            + _tmp85 * _tmp87
            + _tmp88 * _tmp90
            + _tmp94 * _tmp96;
        let _tmp107: T = _tmp68 + _tmp69;
        let _tmp108: T = _tmp57 * (-_tmp2 - _tmp4) + T::one();
        let _tmp109: T = -_tmp91 + _tmp93;
        let _tmp110: T = -_tmp73 - _tmp97 + T::one();
        let _tmp111: T = _tmp81 + _tmp83;
        let _tmp112: T = _tmp100 - _tmp101;
        let _tmp113: T = _tmp110 * covariance[(2, 0)]
            + _tmp111 * covariance[(0, 0)]
            + _tmp112 * covariance[(1, 0)];
        let _tmp114: T = _tmp110 * covariance[(2, 1)]
            + _tmp111 * covariance[(1, 0)]
            + _tmp112 * covariance[(1, 1)];
        let _tmp115: T = _tmp110 * covariance[(2, 2)]
            + _tmp111 * covariance[(2, 0)]
            + _tmp112 * covariance[(2, 1)];
        let _tmp116: T = _tmp107 * _tmp90
            + _tmp108 * _tmp96
            + _tmp109 * _tmp87
            + _tmp113 * _tmp75
            + _tmp114 * _tmp80
            + _tmp115 * _tmp84;
        let _tmp117: T = -_tmp32 * dt;
        let _tmp118: T = -_tmp117 * _tmp22 + _tmp27 * _tmp29 * dt;
        let _tmp119: T = _tmp118 * covariance[(0, 0)];
        let _tmp120: T = _tmp29 * dt;
        let _tmp121: T = _tmp117 * _tmp33 - _tmp120 * _tmp36;
        let _tmp122: T = _tmp121 * covariance[(1, 0)];
        let _tmp123: T = _tmp33 * dt;
        let _tmp124: T = -_tmp123 * _tmp27 + _tmp22 * _tmp36 * dt;
        let _tmp125: T = _tmp124 * covariance[(2, 0)];
        let _tmp126: T = _tmp119 + _tmp122 + _tmp125 + covariance[(3, 0)];
        let _tmp127: T = _tmp118 * covariance[(1, 0)];
        let _tmp128: T = _tmp121 * covariance[(1, 1)];
        let _tmp129: T = _tmp124 * covariance[(2, 1)];
        let _tmp130: T = _tmp127 + _tmp128 + _tmp129 + covariance[(3, 1)];
        let _tmp131: T = _tmp118 * covariance[(2, 0)];
        let _tmp132: T = _tmp121 * covariance[(2, 1)];
        let _tmp133: T = _tmp124 * covariance[(2, 2)];
        let _tmp134: T = _tmp131 + _tmp132 + _tmp133 + covariance[(3, 2)];
        let _tmp135: T = _tmp126 * _tmp75 + _tmp130 * _tmp80 + _tmp134 * _tmp84;
        let _tmp136: T = -_tmp39;
        let _tmp137: T = -_tmp120 * _tmp136 + _tmp123 * _tmp42;
        let _tmp138: T = _tmp137 * covariance[(1, 0)];
        let _tmp139: T = _tmp22 * dt;
        let _tmp140: T = -_tmp139 * _tmp42 + _tmp29 * _tmp45 * dt;
        let _tmp141: T = _tmp140 * covariance[(0, 0)];
        let _tmp142: T = -_tmp123 * _tmp45 + _tmp136 * _tmp22 * dt;
        let _tmp143: T = _tmp142 * covariance[(2, 0)];
        let _tmp144: T = _tmp138 + _tmp141 + _tmp143 + covariance[(4, 0)];
        let _tmp145: T = _tmp137 * covariance[(1, 1)];
        let _tmp146: T = _tmp140 * covariance[(1, 0)];
        let _tmp147: T = _tmp142 * covariance[(2, 1)];
        let _tmp148: T = _tmp145 + _tmp146 + _tmp147 + covariance[(4, 1)];
        let _tmp149: T = _tmp137 * covariance[(2, 1)];
        let _tmp150: T = _tmp140 * covariance[(2, 0)];
        let _tmp151: T = _tmp142 * covariance[(2, 2)];
        let _tmp152: T = _tmp149 + _tmp150 + _tmp151 + covariance[(4, 2)];
        let _tmp153: T = _tmp144 * _tmp75 + _tmp148 * _tmp80 + _tmp152 * _tmp84;
        let _tmp154: T = -_tmp50;
        let _tmp155: T = -_tmp123 * _tmp154 + _tmp22 * _tmp48 * dt;
        let _tmp156: T = _tmp155 * covariance[(2, 0)];
        let _tmp157: T = -_tmp139 * _tmp51 + _tmp154 * _tmp29 * dt;
        let _tmp158: T = _tmp157 * covariance[(0, 0)];
        let _tmp159: T = -_tmp120 * _tmp48 + _tmp123 * _tmp51;
        let _tmp160: T = _tmp159 * covariance[(1, 0)];
        let _tmp161: T = _tmp156 + _tmp158 + _tmp160 + covariance[(5, 0)];
        let _tmp162: T = _tmp155 * covariance[(2, 1)];
        let _tmp163: T = _tmp157 * covariance[(1, 0)];
        let _tmp164: T = _tmp159 * covariance[(1, 1)];
        let _tmp165: T = _tmp162 + _tmp163 + _tmp164 + covariance[(5, 1)];
        let _tmp166: T = _tmp155 * covariance[(2, 2)];
        let _tmp167: T = _tmp157 * covariance[(2, 0)];
        let _tmp168: T = _tmp159 * covariance[(2, 1)];
        let _tmp169: T = _tmp166 + _tmp167 + _tmp168 + covariance[(5, 2)];
        let _tmp170: T = _tmp161 * _tmp75 + _tmp165 * _tmp80 + _tmp169 * _tmp84;
        let _tmp171: T = covariance[(3, 0)] * dt;
        let _tmp172: T = (T::one() / (T::one() + T::one())) * dt;
        let _tmp173: T = _tmp119 * _tmp172
            + _tmp122 * _tmp172
            + _tmp125 * _tmp172
            + _tmp171
            + covariance[(6, 0)];
        let _tmp174: T = covariance[(3, 1)] * dt;
        let _tmp175: T = _tmp127 * _tmp172
            + _tmp128 * _tmp172
            + _tmp129 * _tmp172
            + _tmp174
            + covariance[(6, 1)];
        let _tmp176: T = covariance[(3, 2)] * dt;
        let _tmp177: T = _tmp131 * _tmp172
            + _tmp132 * _tmp172
            + _tmp133 * _tmp172
            + _tmp176
            + covariance[(6, 2)];
        let _tmp178: T = _tmp173 * _tmp75 + _tmp175 * _tmp80 + _tmp177 * _tmp84;
        let _tmp179: T = covariance[(4, 0)] * dt;
        let _tmp180: T = _tmp138 * _tmp172
            + _tmp141 * _tmp172
            + _tmp143 * _tmp172
            + _tmp179
            + covariance[(7, 0)];
        let _tmp181: T = covariance[(4, 1)] * dt;
        let _tmp182: T = _tmp145 * _tmp172
            + _tmp146 * _tmp172
            + _tmp147 * _tmp172
            + _tmp181
            + covariance[(7, 1)];
        let _tmp183: T = covariance[(4, 2)] * dt;
        let _tmp184: T = _tmp149 * _tmp172
            + _tmp150 * _tmp172
            + _tmp151 * _tmp172
            + _tmp183
            + covariance[(7, 2)];
        let _tmp185: T = _tmp180 * _tmp75 + _tmp182 * _tmp80 + _tmp184 * _tmp84;
        let _tmp186: T = covariance[(5, 0)] * dt;
        let _tmp187: T = _tmp156 * _tmp172
            + _tmp158 * _tmp172
            + _tmp160 * _tmp172
            + _tmp186
            + covariance[(8, 0)];
        let _tmp188: T = covariance[(5, 1)] * dt;
        let _tmp189: T = _tmp162 * _tmp172
            + _tmp163 * _tmp172
            + _tmp164 * _tmp172
            + _tmp188
            + covariance[(8, 1)];
        let _tmp190: T = covariance[(5, 2)] * dt;
        let _tmp191: T = _tmp166 * _tmp172
            + _tmp167 * _tmp172
            + _tmp168 * _tmp172
            + _tmp190
            + covariance[(8, 2)];
        let _tmp192: T = _tmp187 * _tmp75 + _tmp189 * _tmp80 + _tmp191 * _tmp84;
        let _tmp193: T = _tmp94 * dt;
        let _tmp194: T = _tmp85 * dt;
        let _tmp195: T = _tmp88 * dt;
        let _tmp196: T = _tmp102 * _tmp115
            + _tmp107 * _tmp195 * gyro_cov_diagonal[0]
            + _tmp108 * _tmp193 * gyro_cov_diagonal[2]
            + _tmp109 * _tmp194 * gyro_cov_diagonal[1]
            + _tmp113 * _tmp99
            + _tmp114 * _tmp98;
        let _tmp197: T = _tmp102 * _tmp134 + _tmp126 * _tmp99 + _tmp130 * _tmp98;
        let _tmp198: T = _tmp102 * _tmp152 + _tmp144 * _tmp99 + _tmp148 * _tmp98;
        let _tmp199: T = _tmp102 * _tmp169 + _tmp161 * _tmp99 + _tmp165 * _tmp98;
        let _tmp200: T = _tmp102 * _tmp177 + _tmp173 * _tmp99 + _tmp175 * _tmp98;
        let _tmp201: T = _tmp102 * _tmp184 + _tmp180 * _tmp99 + _tmp182 * _tmp98;
        let _tmp202: T = _tmp102 * _tmp191 + _tmp187 * _tmp99 + _tmp189 * _tmp98;
        let _tmp203: T = _tmp110 * _tmp134 + _tmp111 * _tmp126 + _tmp112 * _tmp130;
        let _tmp204: T = _tmp110 * _tmp152 + _tmp111 * _tmp144 + _tmp112 * _tmp148;
        let _tmp205: T = _tmp110 * _tmp169 + _tmp111 * _tmp161 + _tmp112 * _tmp165;
        let _tmp206: T = _tmp110 * _tmp177 + _tmp111 * _tmp173 + _tmp112 * _tmp175;
        let _tmp207: T = _tmp110 * _tmp184 + _tmp111 * _tmp180 + _tmp112 * _tmp182;
        let _tmp208: T = _tmp110 * _tmp191 + _tmp111 * _tmp187 + _tmp112 * _tmp189;
        let _tmp209: T = (_tmp28 * _tmp28);
        let _tmp210: T = accel_cov_diagonal[1] * dt;
        let _tmp211: T = (_tmp32 * _tmp32);
        let _tmp212: T = accel_cov_diagonal[2] * dt;
        let _tmp213: T = (_tmp37 * _tmp37);
        let _tmp214: T = accel_cov_diagonal[0] * dt;
        let _tmp215: T = _tmp32 * dt;
        let _tmp216: T = _tmp215 * accel_cov_diagonal[2];
        let _tmp217: T = _tmp37 * dt;
        let _tmp218: T = _tmp217 * accel_cov_diagonal[0];
        let _tmp219: T = _tmp28 * dt;
        let _tmp220: T = _tmp219 * accel_cov_diagonal[1];
        let _tmp221: T = _tmp118 * _tmp144
            + _tmp121 * _tmp148
            + _tmp124 * _tmp152
            + _tmp137 * covariance[(3, 1)]
            + _tmp140 * covariance[(3, 0)]
            + _tmp142 * covariance[(3, 2)]
            + _tmp216 * _tmp43
            + _tmp218 * _tmp39
            + _tmp220 * _tmp46
            + covariance[(4, 3)];
        let _tmp222: T = _tmp118 * _tmp161
            + _tmp121 * _tmp165
            + _tmp124 * _tmp169
            + _tmp155 * covariance[(3, 2)]
            + _tmp157 * covariance[(3, 0)]
            + _tmp159 * covariance[(3, 1)]
            + _tmp216 * _tmp52
            + _tmp218 * _tmp49
            + _tmp220 * _tmp50
            + covariance[(5, 3)];
        let _tmp223: T = _tmp121 * _tmp175;
        let _tmp224: T = _tmp124 * _tmp177;
        let _tmp225: T = _tmp118 * _tmp173;
        let _tmp226: T = _tmp54 * accel_cov_diagonal[0];
        let _tmp227: T = _tmp54 * accel_cov_diagonal[1];
        let _tmp228: T = _tmp54 * accel_cov_diagonal[2];
        let _tmp229: T = (T::one() / (T::one() + T::one())) * _tmp171;
        let _tmp230: T = (T::one() / (T::one() + T::one())) * _tmp174;
        let _tmp231: T = (T::one() / (T::one() + T::one())) * _tmp176;
        let _tmp232: T = _tmp118 * _tmp229
            + _tmp121 * _tmp230
            + _tmp124 * _tmp231
            + covariance[(3, 3)] * dt
            + covariance[(6, 3)];
        let _tmp233: T = _tmp209 * _tmp227
            + _tmp211 * _tmp228
            + _tmp213 * _tmp226
            + _tmp223
            + _tmp224
            + _tmp225
            + _tmp232;
        let _tmp234: T = _tmp121 * _tmp182;
        let _tmp235: T = _tmp124 * _tmp184;
        let _tmp236: T = _tmp118 * _tmp180;
        let _tmp237: T = covariance[(4, 3)] * dt;
        let _tmp238: T = _tmp137 * _tmp230
            + _tmp140 * _tmp229
            + _tmp142 * _tmp231
            + _tmp237
            + covariance[(7, 3)];
        let _tmp239: T = _tmp37 * _tmp54;
        let _tmp240: T = _tmp28 * _tmp54;
        let _tmp241: T = _tmp32 * _tmp54;
        let _tmp242: T = _tmp239 * _tmp39 * accel_cov_diagonal[0]
            + _tmp240 * _tmp46 * accel_cov_diagonal[1]
            + _tmp241 * _tmp43 * accel_cov_diagonal[2];
        let _tmp243: T = _tmp234 + _tmp235 + _tmp236 + _tmp238 + _tmp242;
        let _tmp244: T = _tmp121 * _tmp189;
        let _tmp245: T = _tmp124 * _tmp191;
        let _tmp246: T = _tmp118 * _tmp187;
        let _tmp247: T = covariance[(5, 3)] * dt;
        let _tmp248: T = _tmp155 * _tmp231
            + _tmp157 * _tmp229
            + _tmp159 * _tmp230
            + _tmp247
            + covariance[(8, 3)];
        let _tmp249: T = _tmp49 * accel_cov_diagonal[0];
        let _tmp250: T = _tmp50 * accel_cov_diagonal[1];
        let _tmp251: T = _tmp52 * accel_cov_diagonal[2];
        let _tmp252: T = _tmp239 * _tmp249 + _tmp240 * _tmp250 + _tmp241 * _tmp251;
        let _tmp253: T = _tmp244 + _tmp245 + _tmp246 + _tmp248 + _tmp252;
        let _tmp254: T = (_tmp39 * _tmp39);
        let _tmp255: T = (_tmp43 * _tmp43);
        let _tmp256: T = (_tmp46 * _tmp46);
        let _tmp257: T = _tmp39 * dt;
        let _tmp258: T = _tmp46 * dt;
        let _tmp259: T = _tmp43 * dt;
        let _tmp260: T = _tmp137 * _tmp165
            + _tmp140 * _tmp161
            + _tmp142 * _tmp169
            + _tmp155 * covariance[(4, 2)]
            + _tmp157 * covariance[(4, 0)]
            + _tmp159 * covariance[(4, 1)]
            + _tmp249 * _tmp257
            + _tmp250 * _tmp258
            + _tmp251 * _tmp259
            + covariance[(5, 4)];
        let _tmp261: T = (T::one() / (T::one() + T::one())) * _tmp179;
        let _tmp262: T = (T::one() / (T::one() + T::one())) * _tmp181;
        let _tmp263: T = (T::one() / (T::one() + T::one())) * _tmp183;
        let _tmp264: T = _tmp118 * _tmp261
            + _tmp121 * _tmp262
            + _tmp124 * _tmp263
            + _tmp137 * _tmp175
            + _tmp140 * _tmp173
            + _tmp142 * _tmp177
            + _tmp237
            + _tmp242
            + covariance[(6, 4)];
        let _tmp265: T = _tmp137 * _tmp182;
        let _tmp266: T = _tmp142 * _tmp184;
        let _tmp267: T = _tmp140 * _tmp180;
        let _tmp268: T = _tmp137 * _tmp262
            + _tmp140 * _tmp261
            + _tmp142 * _tmp263
            + covariance[(4, 4)] * dt
            + covariance[(7, 4)];
        let _tmp269: T = _tmp226 * _tmp254
            + _tmp227 * _tmp256
            + _tmp228 * _tmp255
            + _tmp265
            + _tmp266
            + _tmp267
            + _tmp268;
        let _tmp270: T = _tmp137 * _tmp189;
        let _tmp271: T = _tmp142 * _tmp191;
        let _tmp272: T = _tmp140 * _tmp187;
        let _tmp273: T = covariance[(5, 4)] * dt;
        let _tmp274: T = _tmp155 * _tmp263
            + _tmp157 * _tmp261
            + _tmp159 * _tmp262
            + _tmp273
            + covariance[(8, 4)];
        let _tmp275: T = _tmp39 * _tmp54;
        let _tmp276: T = _tmp46 * _tmp54;
        let _tmp277: T = _tmp43 * _tmp54;
        let _tmp278: T = _tmp249 * _tmp275 + _tmp250 * _tmp276 + _tmp251 * _tmp277;
        let _tmp279: T = _tmp270 + _tmp271 + _tmp272 + _tmp274 + _tmp278;
        let _tmp280: T = (_tmp49 * _tmp49);
        let _tmp281: T = (_tmp50 * _tmp50);
        let _tmp282: T = (_tmp52 * _tmp52);
        let _tmp283: T = (T::one() / (T::one() + T::one())) * _tmp186;
        let _tmp284: T = (T::one() / (T::one() + T::one())) * _tmp188;
        let _tmp285: T = (T::one() / (T::one() + T::one())) * _tmp190;
        let _tmp286: T = _tmp118 * _tmp283
            + _tmp121 * _tmp284
            + _tmp124 * _tmp285
            + _tmp155 * _tmp177
            + _tmp157 * _tmp173
            + _tmp159 * _tmp175
            + _tmp247
            + _tmp252
            + covariance[(6, 5)];
        let _tmp287: T = _tmp137 * _tmp284
            + _tmp140 * _tmp283
            + _tmp142 * _tmp285
            + _tmp155 * _tmp184
            + _tmp157 * _tmp180
            + _tmp159 * _tmp182
            + _tmp273
            + _tmp278
            + covariance[(7, 5)];
        let _tmp288: T = _tmp159 * _tmp189;
        let _tmp289: T = _tmp155 * _tmp191;
        let _tmp290: T = _tmp157 * _tmp187;
        let _tmp291: T = _tmp155 * _tmp285
            + _tmp157 * _tmp283
            + _tmp159 * _tmp284
            + covariance[(5, 5)] * dt
            + covariance[(8, 5)];
        let _tmp292: T = _tmp226 * _tmp280
            + _tmp227 * _tmp281
            + _tmp228 * _tmp282
            + _tmp288
            + _tmp289
            + _tmp290
            + _tmp291;
        let _tmp293: T = (T::one() / (T::one() + T::one() + T::one() + T::one())) * (dt * dt * dt);
        let _tmp294: T = _tmp293 * accel_cov_diagonal[1];
        let _tmp295: T = _tmp293 * accel_cov_diagonal[2];
        let _tmp296: T = _tmp293 * accel_cov_diagonal[0];
        let _tmp297: T = _tmp172 * covariance[(6, 0)];
        let _tmp298: T = _tmp172 * covariance[(6, 1)];
        let _tmp299: T = _tmp172 * covariance[(6, 2)];
        let _tmp300: T = _tmp137 * _tmp298
            + _tmp140 * _tmp297
            + _tmp142 * _tmp299
            + _tmp172 * _tmp234
            + _tmp172 * _tmp235
            + _tmp172 * _tmp236
            + _tmp238 * dt
            + _tmp28 * _tmp294 * _tmp46
            + _tmp295 * _tmp32 * _tmp43
            + _tmp296 * _tmp37 * _tmp39
            + covariance[(6, 4)] * dt
            + covariance[(7, 6)];
        let _tmp301: T = _tmp250 * _tmp293;
        let _tmp302: T = _tmp249 * _tmp293;
        let _tmp303: T = _tmp251 * _tmp293;
        let _tmp304: T = _tmp155 * _tmp299
            + _tmp157 * _tmp297
            + _tmp159 * _tmp298
            + _tmp172 * _tmp244
            + _tmp172 * _tmp245
            + _tmp172 * _tmp246
            + _tmp248 * dt
            + _tmp28 * _tmp301
            + _tmp302 * _tmp37
            + _tmp303 * _tmp32
            + covariance[(6, 5)] * dt
            + covariance[(8, 6)];
        let _tmp305: T = _tmp172 * covariance[(7, 1)];
        let _tmp306: T = _tmp172 * covariance[(7, 0)];
        let _tmp307: T = _tmp172 * covariance[(7, 2)];
        let _tmp308: T = _tmp155 * _tmp307
            + _tmp157 * _tmp306
            + _tmp159 * _tmp305
            + _tmp172 * _tmp270
            + _tmp172 * _tmp271
            + _tmp172 * _tmp272
            + _tmp274 * dt
            + _tmp301 * _tmp46
            + _tmp302 * _tmp39
            + _tmp303 * _tmp43
            + covariance[(7, 5)] * dt
            + covariance[(8, 7)];
        let _tmp309: T = DR_D_gyro_bias[(0, 0)] * _tmp118;
        let _tmp310: T = DR_D_gyro_bias[(1, 0)] * _tmp121;
        let _tmp311: T = DR_D_gyro_bias[(2, 0)] * _tmp124;
        let _tmp312: T = DR_D_gyro_bias[(1, 0)] * _tmp137;
        let _tmp313: T = DR_D_gyro_bias[(0, 0)] * _tmp140;
        let _tmp314: T = DR_D_gyro_bias[(2, 0)] * _tmp142;
        let _tmp315: T = DR_D_gyro_bias[(2, 0)] * _tmp155;
        let _tmp316: T = DR_D_gyro_bias[(0, 0)] * _tmp157;
        let _tmp317: T = DR_D_gyro_bias[(1, 0)] * _tmp159;
        let _tmp318: T = DR_D_gyro_bias[(0, 1)] * _tmp118;
        let _tmp319: T = DR_D_gyro_bias[(1, 1)] * _tmp121;
        let _tmp320: T = DR_D_gyro_bias[(2, 1)] * _tmp124;
        let _tmp321: T = DR_D_gyro_bias[(1, 1)] * _tmp137;
        let _tmp322: T = DR_D_gyro_bias[(0, 1)] * _tmp140;
        let _tmp323: T = DR_D_gyro_bias[(2, 1)] * _tmp142;
        let _tmp324: T = DR_D_gyro_bias[(2, 1)] * _tmp155;
        let _tmp325: T = DR_D_gyro_bias[(0, 1)] * _tmp157;
        let _tmp326: T = DR_D_gyro_bias[(1, 1)] * _tmp159;
        let _tmp327: T = DR_D_gyro_bias[(0, 2)] * _tmp118;
        let _tmp328: T = DR_D_gyro_bias[(1, 2)] * _tmp121;
        let _tmp329: T = DR_D_gyro_bias[(2, 2)] * _tmp124;
        let _tmp330: T = DR_D_gyro_bias[(1, 2)] * _tmp137;
        let _tmp331: T = DR_D_gyro_bias[(0, 2)] * _tmp140;
        let _tmp332: T = DR_D_gyro_bias[(2, 2)] * _tmp142;
        let _tmp333: T = DR_D_gyro_bias[(2, 2)] * _tmp155;
        let _tmp334: T = DR_D_gyro_bias[(0, 2)] * _tmp157;
        let _tmp335: T = DR_D_gyro_bias[(1, 2)] * _tmp159;

        // Output terms (9)
        if let Some(new_DR) = new_DR {
            *new_DR = stack_algebra::Matrix::<4, 1, T>::zeros();
            new_DR[0] = _DR[0] * _tmp12 + _DR[1] * _tmp18 + _tmp1 * _tmp16 - _tmp19 * _tmp3;
            new_DR[1] = -_DR[0] * _tmp18 + _DR[1] * _tmp12 + _tmp1 * _tmp19 + _tmp16 * _tmp3;
            new_DR[2] = _DR[2] * _tmp12 + _DR[3] * _tmp18 - _tmp1 * _tmp21 + _tmp20 * _tmp3;
            new_DR[3] = -_DR[2] * _tmp18 + _DR[3] * _tmp12 - _tmp1 * _tmp20 - _tmp21 * _tmp3;
        }

        if let Some(new_Dv) = new_Dv {
            *new_Dv = stack_algebra::Matrix::<3, 1, T>::zeros();
            new_Dv[0] = Dv[0] + _tmp38 * dt;
            new_Dv[1] = Dv[1] + _tmp47 * dt;
            new_Dv[2] = Dv[2] + _tmp53 * dt;
        }

        if let Some(new_Dp) = new_Dp {
            *new_Dp = stack_algebra::Matrix::<3, 1, T>::zeros();
            new_Dp[0] = Dp[0] + Dv[0] * dt + _tmp38 * _tmp54;
            new_Dp[1] = Dp[1] + Dv[1] * dt + _tmp47 * _tmp54;
            new_Dp[2] = Dp[2] + Dv[2] * dt + _tmp53 * _tmp54;
        }

        if let Some(new_covariance) = new_covariance {
            *new_covariance = stack_algebra::Matrix::<9, 9, T>::zeros();
            new_covariance[(0, 0)] = (_tmp58 * _tmp58) * _tmp59
                + (_tmp65 * _tmp65) * _tmp66
                + (_tmp70 * _tmp70) * _tmp71
                + _tmp75
                    * (_tmp75 * covariance[(0, 0)]
                        + _tmp80 * covariance[(1, 0)]
                        + _tmp84 * covariance[(2, 0)])
                + _tmp80
                    * (_tmp75 * covariance[(1, 0)]
                        + _tmp80 * covariance[(1, 1)]
                        + _tmp84 * covariance[(2, 1)])
                + _tmp84
                    * (_tmp75 * covariance[(2, 0)]
                        + _tmp80 * covariance[(2, 1)]
                        + _tmp84 * covariance[(2, 2)]);
            new_covariance[(1, 0)] = _tmp106;
            new_covariance[(2, 0)] = _tmp116;
            new_covariance[(3, 0)] = _tmp135;
            new_covariance[(4, 0)] = _tmp153;
            new_covariance[(5, 0)] = _tmp170;
            new_covariance[(6, 0)] = _tmp178;
            new_covariance[(7, 0)] = _tmp185;
            new_covariance[(8, 0)] = _tmp192;
            new_covariance[(0, 1)] = _tmp106;
            new_covariance[(1, 1)] = _tmp102 * _tmp105
                + _tmp103 * _tmp99
                + _tmp104 * _tmp98
                + _tmp59 * (_tmp88 * _tmp88)
                + _tmp66 * (_tmp85 * _tmp85)
                + _tmp71 * (_tmp94 * _tmp94);
            new_covariance[(2, 1)] = _tmp196;
            new_covariance[(3, 1)] = _tmp197;
            new_covariance[(4, 1)] = _tmp198;
            new_covariance[(5, 1)] = _tmp199;
            new_covariance[(6, 1)] = _tmp200;
            new_covariance[(7, 1)] = _tmp201;
            new_covariance[(8, 1)] = _tmp202;
            new_covariance[(0, 2)] = _tmp116;
            new_covariance[(1, 2)] = _tmp196;
            new_covariance[(2, 2)] = (_tmp107 * _tmp107) * _tmp59
                + (_tmp108 * _tmp108) * _tmp71
                + (_tmp109 * _tmp109) * _tmp66
                + _tmp110 * _tmp115
                + _tmp111 * _tmp113
                + _tmp112 * _tmp114;
            new_covariance[(3, 2)] = _tmp203;
            new_covariance[(4, 2)] = _tmp204;
            new_covariance[(5, 2)] = _tmp205;
            new_covariance[(6, 2)] = _tmp206;
            new_covariance[(7, 2)] = _tmp207;
            new_covariance[(8, 2)] = _tmp208;
            new_covariance[(0, 3)] = _tmp135;
            new_covariance[(1, 3)] = _tmp197;
            new_covariance[(2, 3)] = _tmp203;
            new_covariance[(3, 3)] = _tmp118 * _tmp126
                + _tmp118 * covariance[(3, 0)]
                + _tmp121 * _tmp130
                + _tmp121 * covariance[(3, 1)]
                + _tmp124 * _tmp134
                + _tmp124 * covariance[(3, 2)]
                + _tmp209 * _tmp210
                + _tmp211 * _tmp212
                + _tmp213 * _tmp214
                + covariance[(3, 3)];
            new_covariance[(4, 3)] = _tmp221;
            new_covariance[(5, 3)] = _tmp222;
            new_covariance[(6, 3)] = _tmp233;
            new_covariance[(7, 3)] = _tmp243;
            new_covariance[(8, 3)] = _tmp253;
            new_covariance[(0, 4)] = _tmp153;
            new_covariance[(1, 4)] = _tmp198;
            new_covariance[(2, 4)] = _tmp204;
            new_covariance[(3, 4)] = _tmp221;
            new_covariance[(4, 4)] = _tmp137 * _tmp148
                + _tmp137 * covariance[(4, 1)]
                + _tmp140 * _tmp144
                + _tmp140 * covariance[(4, 0)]
                + _tmp142 * _tmp152
                + _tmp142 * covariance[(4, 2)]
                + _tmp210 * _tmp256
                + _tmp212 * _tmp255
                + _tmp214 * _tmp254
                + covariance[(4, 4)];
            new_covariance[(5, 4)] = _tmp260;
            new_covariance[(6, 4)] = _tmp264;
            new_covariance[(7, 4)] = _tmp269;
            new_covariance[(8, 4)] = _tmp279;
            new_covariance[(0, 5)] = _tmp170;
            new_covariance[(1, 5)] = _tmp199;
            new_covariance[(2, 5)] = _tmp205;
            new_covariance[(3, 5)] = _tmp222;
            new_covariance[(4, 5)] = _tmp260;
            new_covariance[(5, 5)] = _tmp155 * _tmp169
                + _tmp155 * covariance[(5, 2)]
                + _tmp157 * _tmp161
                + _tmp157 * covariance[(5, 0)]
                + _tmp159 * _tmp165
                + _tmp159 * covariance[(5, 1)]
                + _tmp210 * _tmp281
                + _tmp212 * _tmp282
                + _tmp214 * _tmp280
                + covariance[(5, 5)];
            new_covariance[(6, 5)] = _tmp286;
            new_covariance[(7, 5)] = _tmp287;
            new_covariance[(8, 5)] = _tmp292;
            new_covariance[(0, 6)] = _tmp178;
            new_covariance[(1, 6)] = _tmp200;
            new_covariance[(2, 6)] = _tmp206;
            new_covariance[(3, 6)] = _tmp233;
            new_covariance[(4, 6)] = _tmp264;
            new_covariance[(5, 6)] = _tmp286;
            new_covariance[(6, 6)] = _tmp118 * _tmp297
                + _tmp121 * _tmp298
                + _tmp124 * _tmp299
                + _tmp172 * _tmp223
                + _tmp172 * _tmp224
                + _tmp172 * _tmp225
                + _tmp209 * _tmp294
                + _tmp211 * _tmp295
                + _tmp213 * _tmp296
                + _tmp232 * dt
                + covariance[(6, 3)] * dt
                + covariance[(6, 6)];
            new_covariance[(7, 6)] = _tmp300;
            new_covariance[(8, 6)] = _tmp304;
            new_covariance[(0, 7)] = _tmp185;
            new_covariance[(1, 7)] = _tmp201;
            new_covariance[(2, 7)] = _tmp207;
            new_covariance[(3, 7)] = _tmp243;
            new_covariance[(4, 7)] = _tmp269;
            new_covariance[(5, 7)] = _tmp287;
            new_covariance[(6, 7)] = _tmp300;
            new_covariance[(7, 7)] = _tmp137 * _tmp305
                + _tmp140 * _tmp306
                + _tmp142 * _tmp307
                + _tmp172 * _tmp265
                + _tmp172 * _tmp266
                + _tmp172 * _tmp267
                + _tmp254 * _tmp296
                + _tmp255 * _tmp295
                + _tmp256 * _tmp294
                + _tmp268 * dt
                + covariance[(7, 4)] * dt
                + covariance[(7, 7)];
            new_covariance[(8, 7)] = _tmp308;
            new_covariance[(0, 8)] = _tmp192;
            new_covariance[(1, 8)] = _tmp202;
            new_covariance[(2, 8)] = _tmp208;
            new_covariance[(3, 8)] = _tmp253;
            new_covariance[(4, 8)] = _tmp279;
            new_covariance[(5, 8)] = _tmp292;
            new_covariance[(6, 8)] = _tmp304;
            new_covariance[(7, 8)] = _tmp308;
            new_covariance[(8, 8)] = _tmp155 * _tmp172 * covariance[(8, 2)]
                + _tmp157 * _tmp172 * covariance[(8, 0)]
                + _tmp159 * _tmp172 * covariance[(8, 1)]
                + _tmp172 * _tmp288
                + _tmp172 * _tmp289
                + _tmp172 * _tmp290
                + _tmp280 * _tmp296
                + _tmp281 * _tmp294
                + _tmp282 * _tmp295
                + _tmp291 * dt
                + covariance[(8, 5)] * dt
                + covariance[(8, 8)];
        }

        if let Some(new_DR_D_gyro_bias) = new_DR_D_gyro_bias {
            *new_DR_D_gyro_bias = stack_algebra::Matrix::<3, 3, T>::zeros();
            new_DR_D_gyro_bias[(0, 0)] = DR_D_gyro_bias[(0, 0)] * _tmp75
                + DR_D_gyro_bias[(1, 0)] * _tmp80
                + DR_D_gyro_bias[(2, 0)] * _tmp84
                - _tmp89;
            new_DR_D_gyro_bias[(1, 0)] = DR_D_gyro_bias[(0, 0)] * _tmp99
                + DR_D_gyro_bias[(1, 0)] * _tmp98
                + DR_D_gyro_bias[(2, 0)] * _tmp102
                - _tmp195;
            new_DR_D_gyro_bias[(2, 0)] = DR_D_gyro_bias[(0, 0)] * _tmp111
                + DR_D_gyro_bias[(1, 0)] * _tmp112
                + DR_D_gyro_bias[(2, 0)] * _tmp110
                - _tmp107 * dt;
            new_DR_D_gyro_bias[(0, 1)] = DR_D_gyro_bias[(0, 1)] * _tmp75
                + DR_D_gyro_bias[(1, 1)] * _tmp80
                + DR_D_gyro_bias[(2, 1)] * _tmp84
                - _tmp86;
            new_DR_D_gyro_bias[(1, 1)] = DR_D_gyro_bias[(0, 1)] * _tmp99
                + DR_D_gyro_bias[(1, 1)] * _tmp98
                + DR_D_gyro_bias[(2, 1)] * _tmp102
                - _tmp194;
            new_DR_D_gyro_bias[(2, 1)] = DR_D_gyro_bias[(0, 1)] * _tmp111
                + DR_D_gyro_bias[(1, 1)] * _tmp112
                + DR_D_gyro_bias[(2, 1)] * _tmp110
                - _tmp109 * dt;
            new_DR_D_gyro_bias[(0, 2)] = DR_D_gyro_bias[(0, 2)] * _tmp75
                + DR_D_gyro_bias[(1, 2)] * _tmp80
                + DR_D_gyro_bias[(2, 2)] * _tmp84
                - _tmp95;
            new_DR_D_gyro_bias[(1, 2)] = DR_D_gyro_bias[(0, 2)] * _tmp99
                + DR_D_gyro_bias[(1, 2)] * _tmp98
                + DR_D_gyro_bias[(2, 2)] * _tmp102
                - _tmp193;
            new_DR_D_gyro_bias[(2, 2)] = DR_D_gyro_bias[(0, 2)] * _tmp111
                + DR_D_gyro_bias[(1, 2)] * _tmp112
                + DR_D_gyro_bias[(2, 2)] * _tmp110
                - _tmp108 * dt;
        }

        if let Some(new_Dv_D_accel_bias) = new_Dv_D_accel_bias {
            *new_Dv_D_accel_bias = stack_algebra::Matrix::<3, 3, T>::zeros();
            new_Dv_D_accel_bias[(0, 0)] = Dv_D_accel_bias[(0, 0)] - _tmp217;
            new_Dv_D_accel_bias[(1, 0)] = Dv_D_accel_bias[(1, 0)] - _tmp257;
            new_Dv_D_accel_bias[(2, 0)] = Dv_D_accel_bias[(2, 0)] - _tmp49 * dt;
            new_Dv_D_accel_bias[(0, 1)] = Dv_D_accel_bias[(0, 1)] - _tmp219;
            new_Dv_D_accel_bias[(1, 1)] = Dv_D_accel_bias[(1, 1)] - _tmp258;
            new_Dv_D_accel_bias[(2, 1)] = Dv_D_accel_bias[(2, 1)] - _tmp50 * dt;
            new_Dv_D_accel_bias[(0, 2)] = Dv_D_accel_bias[(0, 2)] - _tmp215;
            new_Dv_D_accel_bias[(1, 2)] = Dv_D_accel_bias[(1, 2)] - _tmp259;
            new_Dv_D_accel_bias[(2, 2)] = Dv_D_accel_bias[(2, 2)] - _tmp52 * dt;
        }

        if let Some(new_Dv_D_gyro_bias) = new_Dv_D_gyro_bias {
            *new_Dv_D_gyro_bias = stack_algebra::Matrix::<3, 3, T>::zeros();
            new_Dv_D_gyro_bias[(0, 0)] = Dv_D_gyro_bias[(0, 0)] + _tmp309 + _tmp310 + _tmp311;
            new_Dv_D_gyro_bias[(1, 0)] = Dv_D_gyro_bias[(1, 0)] + _tmp312 + _tmp313 + _tmp314;
            new_Dv_D_gyro_bias[(2, 0)] = Dv_D_gyro_bias[(2, 0)] + _tmp315 + _tmp316 + _tmp317;
            new_Dv_D_gyro_bias[(0, 1)] = Dv_D_gyro_bias[(0, 1)] + _tmp318 + _tmp319 + _tmp320;
            new_Dv_D_gyro_bias[(1, 1)] = Dv_D_gyro_bias[(1, 1)] + _tmp321 + _tmp322 + _tmp323;
            new_Dv_D_gyro_bias[(2, 1)] = Dv_D_gyro_bias[(2, 1)] + _tmp324 + _tmp325 + _tmp326;
            new_Dv_D_gyro_bias[(0, 2)] = Dv_D_gyro_bias[(0, 2)] + _tmp327 + _tmp328 + _tmp329;
            new_Dv_D_gyro_bias[(1, 2)] = Dv_D_gyro_bias[(1, 2)] + _tmp330 + _tmp331 + _tmp332;
            new_Dv_D_gyro_bias[(2, 2)] = Dv_D_gyro_bias[(2, 2)] + _tmp333 + _tmp334 + _tmp335;
        }

        if let Some(new_Dp_D_accel_bias) = new_Dp_D_accel_bias {
            *new_Dp_D_accel_bias = stack_algebra::Matrix::<3, 3, T>::zeros();
            new_Dp_D_accel_bias[(0, 0)] =
                Dp_D_accel_bias[(0, 0)] + Dv_D_accel_bias[(0, 0)] * dt - _tmp239;
            new_Dp_D_accel_bias[(1, 0)] =
                Dp_D_accel_bias[(1, 0)] + Dv_D_accel_bias[(1, 0)] * dt - _tmp275;
            new_Dp_D_accel_bias[(2, 0)] =
                Dp_D_accel_bias[(2, 0)] + Dv_D_accel_bias[(2, 0)] * dt - _tmp49 * _tmp54;
            new_Dp_D_accel_bias[(0, 1)] =
                Dp_D_accel_bias[(0, 1)] + Dv_D_accel_bias[(0, 1)] * dt - _tmp240;
            new_Dp_D_accel_bias[(1, 1)] =
                Dp_D_accel_bias[(1, 1)] + Dv_D_accel_bias[(1, 1)] * dt - _tmp276;
            new_Dp_D_accel_bias[(2, 1)] =
                Dp_D_accel_bias[(2, 1)] + Dv_D_accel_bias[(2, 1)] * dt - _tmp50 * _tmp54;
            new_Dp_D_accel_bias[(0, 2)] =
                Dp_D_accel_bias[(0, 2)] + Dv_D_accel_bias[(0, 2)] * dt - _tmp241;
            new_Dp_D_accel_bias[(1, 2)] =
                Dp_D_accel_bias[(1, 2)] + Dv_D_accel_bias[(1, 2)] * dt - _tmp277;
            new_Dp_D_accel_bias[(2, 2)] =
                Dp_D_accel_bias[(2, 2)] + Dv_D_accel_bias[(2, 2)] * dt - _tmp52 * _tmp54;
        }

        if let Some(new_Dp_D_gyro_bias) = new_Dp_D_gyro_bias {
            *new_Dp_D_gyro_bias = stack_algebra::Matrix::<3, 3, T>::zeros();
            new_Dp_D_gyro_bias[(0, 0)] = Dp_D_gyro_bias[(0, 0)]
                + Dv_D_gyro_bias[(0, 0)] * dt
                + _tmp172 * _tmp309
                + _tmp172 * _tmp310
                + _tmp172 * _tmp311;
            new_Dp_D_gyro_bias[(1, 0)] = Dp_D_gyro_bias[(1, 0)]
                + Dv_D_gyro_bias[(1, 0)] * dt
                + _tmp172 * _tmp312
                + _tmp172 * _tmp313
                + _tmp172 * _tmp314;
            new_Dp_D_gyro_bias[(2, 0)] = Dp_D_gyro_bias[(2, 0)]
                + Dv_D_gyro_bias[(2, 0)] * dt
                + _tmp172 * _tmp315
                + _tmp172 * _tmp316
                + _tmp172 * _tmp317;
            new_Dp_D_gyro_bias[(0, 1)] = Dp_D_gyro_bias[(0, 1)]
                + Dv_D_gyro_bias[(0, 1)] * dt
                + _tmp172 * _tmp318
                + _tmp172 * _tmp319
                + _tmp172 * _tmp320;
            new_Dp_D_gyro_bias[(1, 1)] = Dp_D_gyro_bias[(1, 1)]
                + Dv_D_gyro_bias[(1, 1)] * dt
                + _tmp172 * _tmp321
                + _tmp172 * _tmp322
                + _tmp172 * _tmp323;
            new_Dp_D_gyro_bias[(2, 1)] = Dp_D_gyro_bias[(2, 1)]
                + Dv_D_gyro_bias[(2, 1)] * dt
                + _tmp172 * _tmp324
                + _tmp172 * _tmp325
                + _tmp172 * _tmp326;
            new_Dp_D_gyro_bias[(0, 2)] = Dp_D_gyro_bias[(0, 2)]
                + Dv_D_gyro_bias[(0, 2)] * dt
                + _tmp172 * _tmp327
                + _tmp172 * _tmp328
                + _tmp172 * _tmp329;
            new_Dp_D_gyro_bias[(1, 2)] = Dp_D_gyro_bias[(1, 2)]
                + Dv_D_gyro_bias[(1, 2)] * dt
                + _tmp172 * _tmp330
                + _tmp172 * _tmp331
                + _tmp172 * _tmp332;
            new_Dp_D_gyro_bias[(2, 2)] = Dp_D_gyro_bias[(2, 2)]
                + Dv_D_gyro_bias[(2, 2)] * dt
                + _tmp172 * _tmp333
                + _tmp172 * _tmp334
                + _tmp172 * _tmp335;
        }
    }
} // mod sym
